apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_WITH_NEON_CONNECTION_STRING"
  SECRET_KEY: "REPLACE_WITH_OPENSSL_RAND_HEX_32"
  MODEL_PATH: "/models/fraud_detector.pkl"
  OTEL_ENDPOINT: "http://jaeger:4317"
