apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: 8000
      targetPort: 8000
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dashboard
spec:
  selector:
    app: {{ .Release.Name }}-dashboard
  ports:
    - port: 8501
      targetPort: 8501
  type: ClusterIP
